test:main.o save.o loadbook.o search.o modify.o display.o statistics.o deletebook.o
	gcc main.o save.o loadbook.o search.o modify.o display.o statistics.o deletebook.o -o test    
main.o:
	gcc -c main.c -o main.o
addbook.o:
	gcc -c addbook.c -o main.o
save.o:
	gcc -c save.c -o save.o
loadbook.o:
	gcc -c loadbook.c -o loadbook.o
search.o:
	gcc -c search.c -o search.o
modify.o:
	gcc -c modify.c -o modify.o
display.o:
	gcc -c display.c -o display.o
deletebook.o:
	gcc -c deletebook.c -o deletebook.o
statistics.o:
	gcc -c statistics.c -o statistics.o
clean:
	rm main.o addbook.o save.o loadbook.o search.o modify.o displau.o deletebook.o statistics.o 
