 main :hehe.h main.o duqu.o chaxun.o tianjia.o xiugai.o shanchu.o xianshi.o tongji.o
	cc -o main -g hehe.h main.o duqu.o chaxun.o tianjia.o xiugai.o shanchu.o xianshi.o tongji.o
 main.o :main.c hehe.h
	cc -c -g main.c
 duqu.o :duqu.c hehe.h
	cc -c -g duqu.c
 chaxun.o :chaxun.c hehe.h
	cc -c -g chaxun.c
 tianjia.o :tianjia.c hehe.h
	cc -c -g tianjia.c
 xiugai.o :xiugai.c hehe.h
	cc -c -g xiugai.c
 shanchu.o :shanchu.c hehe.h
	cc -c -g shanchu.c
 xianshi.o :xianshi.c hehe.h
	cc -c -g xianshi.c
 tongji.o :tongji.c hehe.h
	cc -c -g tongji.c
 clean:
	rm main hehe.h main.o duqu.o chaxun.o tianjia.o xiugai.o shanchu.o xianshi.o tongji.o
