ms :printf.o add.o named.o bim.o delate.o finish.o key.o head.h search.o byisb.o searchkeyword.o
        cc -o bim -g printf.o add.o name.o bim.o delate.o finish.o key.o head.h search.o byisb.o searchkeyword.o
add.o :add.c head.h
        cc -c -g add.c
named.o :name.c head.h
        cc -c -g named.cbim.o :bim.c head.h
        cc -c -g bim.c
delete.o :delete.c head.h
        cc -c -g delete.c
finish.o :finish.c head.h
        cc -c -g finish.c
key.o :key.c head.h
        cc -c -g key.c
search.o :search.c head.h
        cc -c -g search.c
byisb.o :byisb.c head.h
        cc -c -g byisb.c
searchkeyword.o :searchkeyword.c head.h
        cc -c -g searchkeyword.c
printf.o :print.c head.h
