BookMIS:BookMIS.o add.o bload.o change.o cut.o keep.o paixu.o Report.o Search.o 
	gcc -o BookMIS BookMIS.o add.o bload.o change.o cut.o keep.o paixu.o Report.o Search.o
BookMIS.o:
	gcc -c BookMIS.c
add.o:
	gcc -c add.c
bload.o:	
	gcc -c bload.c
change.o:	
	gcc -c change.c
cut.o:	
	gcc -c cut.c
keep.o:	
	gcc -c keep.c
paixu.o:	
	gcc -c paixu.c
Report.o:	
	gcc -c Report.c
Search.o:	
	gcc -c Search.c
BookMIS.o:
	gcc -c BookMIS.c
clean:
	BookMIS.o add.o bload.o change.o cut.o keep.o paixu.o Report.o Search.o
