 pyt: sadstory.h main.o add_book.o borrow.o name_search.o revise.o author_search.o count.o isbn_search.o create.o return.o book_print.o delete.o menu.o return_file.o statistics.o 
	cc -o pyt -g  sadstory.h main.o add_book.o borrow.o name_search.o revise.o author_search.o count.o isbn_search.o create.o return.o book_print.o delete.o menu.o return_file.o statistics.o
 main.o: main.c sadstory.h
	cc -c -g main.c
 add_book.o: add_book.c sadstory.h
	cc -c -g add_book.c
 borrow.o: borrow.c sadstory.h
	cc -c -g borrow.c
 name_search.o: name_search.c sadstory.h
	cc -c -g name_search.c
 revise.o: revise.c sadstory.h
	cc -c -g revise.c
 author_search.o: author_search.c sadstory.h
	cc -c -g author_search.c
 count.o: count.c sadstory.h
	cc -c -g count.c
 isbn_search.o: isbn_search.c sadstory.h
	cc -c -g isbn_search.c
 create.o: create.c sadstory.h
	cc -c -g create.c
 return.o: return.c sadstory.h
	cc -c -g return.c
 book_print.o: book_print.c sadstory.h
	cc -c -g book_print.c
 delete.o: delete.c sadstory.h
	cc -c -g delete.c
 menu.o: menu.c sadstory.h
	cc -c -g menu.c
 return_file.o: return_file.c sadstory.h
	cc -c -g return_file.c
 statistics.o: statistics.c sadstory.h
	cc -c -g statistics.c
 clean:
	rm pyt sadstory.h main.o add_book.o borrow.o name_search.o revise.o author_search.o count.o isbn_search.o create.o return.o book_print.o delete.o menu.o return_file.o statistics.o
