main :大礼包.h main.o zhibiao.o chaxun.o tianjia.o xiugai.o shanchu.o xianshi.o tongji.o
	cc -o main -g 大礼包.h main.o zhibiao.o chaxun.o tianjia.o xiugai.o shanchu.o xianshi.o tongji.o
main.o :main.c 大礼包.h
	cc -c -g main.c
zhibiao.o :zhibiao.c 大礼包.h
	cc -c -g zhibiao.c
chaxun.o :chaxun.c 大礼包.h
	cc -c -g chaxun.c
tianjia.o :tianjia.c 大礼包.h
	cc -c -g tianjia.c
xiugai.o :xiugai.c 大礼包.h
	cc -c -g xiugai.c
shanchu.o :shanchu.c 大礼包.h
	cc -c -g shanchu.c
xianshi.o :xianshi.c 大礼包.h
	cc -c -g xianshi.c
tongji.o :tongji.c 大礼包.h
clean:
